yamlversion: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homework_app
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80" # Открывает порт 8080 наружу и связывает с портом 80 nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Монтирует файл конфигурации
    depends_on:
      - app # Запускает nginx только после старта приложения
    restart: always