pipeline {
    agent any // Визначає, що pipeline може виконуватися на будь-якому доступному Jenkins worker

    options {
        timeout(time: 1, unit: 'HOURS') // Захист від зависання
    }

    stages {
        stage('Pull Code') {
            steps {
                echo '--- Крок 1: Отримання коду з репозиторію ---'
                checkout scmGit(
                    branches: [[name: '*/main']], 
                    userRemoteConfigs: [[url: "https://github.com/cadavezne-creator/testov.git"]],
                    extensions: scm.extensions + [[$class: 'CleanCheckout']]
                )
            }
        }

        stage('Build Docker Image') {
            steps {
                echo '--- Крок 2: Збірка Docker-образу ---'
                script {
                    // Збираємо образ за допомогою Dockerfile, який лежить у коліні проекту
                    // Встановлюємо унікальний тег за допомогою номера збірки Jenkins ($BUILD_NUMBER)
                    sh 'docker build -t my-test-app:${BUILD_NUMBER} .'
                    // Авторизація та відправка
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'PiDHub', 
                            usernameVariable: 'DOCKER_USER', 
                            passwordVariable: 'DOCKER_PASS'
                        )
                    ]) {
                        sh "echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin"
                        
                        sh "docker tag my-test-app:${env.BUILD_NUMBER} my-test-app:latest"
                        
                        sh "docker push my-test-app:${env.BUILD_NUMBER}"
                        sh "docker push my-test-app:latest"
                        sh "docker logout"
                        sh 'docker rmi my-test-app:${BUILD_NUMBER}'
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                echo '--- Крок 3: Запуск тестів у Docker-контейнері ---'
                script {
                    try {
                        withCredentials([
                            usernamePassword(
                                credentialsId: 'PiDHub', 
                                usernameVariable: 'DOCKER_USER', 
                                passwordVariable: 'DOCKER_PASS'
                            )
                        ]) {
                            sh "echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin"
                            sh "docker pull my-test-app:${env.BUILD_NUMBER}"
                        }
                        sh 'docker run --rm my-test-app:${BUILD_NUMBER} test'
                    } finally {
                        echo '--- Очищення: Видалення локального Docker-образу ---'
                
                        
                    }
                }
            }
        }
    }   
    post {
        always {
            echo 'Pipeline завершив роботу.'
        }
        success {
            echo 'Тести пройшли успішно! 🎉'
        }
        failure {
            echo 'Сталася помилка під час виконання Pipeline або тести завалилися. ❌'
        }
    }
}