pipeline {
    agent any // Визначає, що pipeline може виконуватися на будь-якому доступному Jenkins worker
    environment {
        DOCKER_IMAGE = "cadavvez/my-test-app" // Змінна для зберігання імені Docker-образу
    }
    options {
        timeout(time: 1, unit: 'HOURS') // Захист від зависання
    }

    stages {
        stage('Pull Code') {
            steps {
                echo '--- Крок 1: Отримання коду з репозиторію ---'
                checkout scmGit(
                    branches: [[name: '*/main']], 
                    userRemoteConfigs: [[url: "https://github.com/cadavezne-creator/testov.git"]],
                    extensions: scm.extensions + [[$class: 'CleanCheckout']]
                )
            }
        }

        stage('Build Docker Image') {
            steps {
                echo '--- Крок 2: Збірка Docker-образу ---'
                script {
                    // собираем образ
                    // тегируем номером сборки
                    sh 'docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} .'
                    // Авторизация
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'PiDHub', 
                            usernameVariable: 'DOCKER_USER', 
                            passwordVariable: 'DOCKER_PASS'
                        )
                    ]) {
                        sh "echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin"
                        
                        sh "docker tag ${DOCKER_IMAGE}:${env.BUILD_NUMBER} ${DOCKER_IMAGE}:latest"
                                                
                        sh "docker push ${DOCKER_IMAGE}:${env.BUILD_NUMBER}"
                        sh "docker push ${DOCKER_IMAGE}:latest"
                        sh "docker logout"

                        sh 'docker rmi ${DOCKER_IMAGE}:${BUILD_NUMBER}'
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                echo '--- Крок 3: Запуск тестів у Docker-контейнері ---'
                script {
                    try {
                        withCredentials([
                            usernamePassword(
                                credentialsId: 'PiDHub', 
                                usernameVariable: 'DOCKER_USER', 
                                passwordVariable: 'DOCKER_PASS'
                            )
                        ]) {
                            sh "echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin"
                            sh "docker pull ${DOCKER_IMAGE}:${env.BUILD_NUMBER}"
                        }
                        sh 'docker run --rm ${DOCKER_IMAGE}:${BUILD_NUMBER} test'
                    } finally {
                        echo '--- Очищення: Видалення локального Docker-образу ---'                      
                    }
                }
            }
        }
    }   
    post {
        always {
            echo 'Pipeline завершив роботу.'
        }
        success {
            echo 'Тести пройшли успішно! 🎉'
        }
        failure {
            echo 'Сталася помилка під час виконання Pipeline або тести завалилися. ❌'
        }
    }
}