pipeline {
    agent {
    any
    } // Визначає, що pipeline може виконуватися на будь-якому доступному Jenkins worker

    options {
        timeout(time: 1, unit: 'HOURS') // Захист від зависання
    }

    stages {
        stage('Pull Code') {
            steps {
                echo '--- Крок 1: Отримання коду з репозиторію ---'
                checkout scmGit(
                    branches: [[name: '*/main']], 
                    userRemoteConfigs: [[url: "https://github.com/cadavezne-creator/testov.git"]]
                )
            }
        }

        stage('Build Docker Image') {
            steps {
                echo '--- Крок 2: Збірка Docker-образу ---'
                script {
                    // Збираємо образ за допомогою Dockerfile, який лежить у коліні проекту
                    // Встановлюємо унікальний тег за допомогою номера збірки Jenkins ($BUILD_NUMBER)
                    sh 'docker build -t my-test-app:${BUILD_NUMBER} .'
                }
            }
        }

        stage('Run Tests') {
            steps {
                echo '--- Крок 3: Запуск тестів у Docker-контейнері ---'
                script {
                    try {
                        
                        sh 'docker run --rm my-test-app:${BUILD_NUMBER} test'
                    } finally {
                        echo '--- Очищення: Видалення локального Docker-образу ---'
                
                        sh 'docker rmi my-test-app:${BUILD_NUMBER}'
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline завершив роботу.'
        }
        success {
            echo 'Тести пройшли успішно! '
        }
        }
    }
}
        }
        failure {
            echo 'Сталася помилка під час виконання Pipeline або тести завалилися. ❌'
        }
    }
}

        stage('Push to Docker Hub') {
            steps {
                script {
            withCredentials([usernamePassword(credentialsId: 'PiDHub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                
                // 1. Авторизація в Docker Hub
                sh "echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin"
                
                // 2. Тегування локального образу my-test-app для репозиторію cadavvez/forstep2
                sh "docker tag my-test-app:latest cadavvez/forstep2:${env.BUILD_NUMBER}"
                sh "docker tag my-test-app:latest cadavvez/forstep2:latest"
                
                // 3. Відправка тегів у Docker Hub
                sh "docker push cadavvez/forstep2:${env.BUILD_NUMBER}"
                sh "docker push cadavvez/forstep2:latest"
                
                // 4. Вихід з Docker Hub задля безпеки
                sh "docker logout"
            }
        }
    }
}